### ISSUE TITLE
YCom User: Feldnamen an HTML5-autocomplete anpassen (Betrifft: name)

### ISSUE THREAD

**Issue by alxndr-w** [yakamara/ycom#216]
https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete

Das `name`-Feld müsste eigentlich `family-name` heißen, wobei in der Praxis auf `lastname` zählt. Dadurch, dass das Feld `name` heißt, wird es per autocomplete mit dem vollen Namen ausgefüllt und ist damit schlechte Usability.

Kann man dieses Feld für zukünftige YCom-Versionen korrigieren?

**Comment by dergel** [comment]
sehr schwierig nachtträglich zu ändern.. ich nehme das aber mal auf zum nachdenken.

**Comment by alexplusde** [comment]
Mir ist bewusst, dass das schwierig ist, weil dann auch Formulare korrigiert werden müssen. Aber es ist m.E. die richtige Entscheidung, es umzubenennen. Leider ist es mir erst nach 3.0 aufgefallen.

**Comment by alexplusde** [comment]
Das hätte man ja bei 4.0 machen können :(
