### ISSUE TITLE
Widgets für das Frontend. 

### ISSUE THREAD

**Issue by skerbis** [yakamara/ycom#330]
Ich weiß nicht ob es hier hin gehört oder eher zu REDAXO selbst.
Thematisch passt es aber zu YCOM, weil das Szenario meist wohl hier vorkommt.   

In den Frontendeingaben benötige ich schon mal: 

- Einen Dataset-Picker (Datensätze aus YFORM auswählen, z.B. News verlinken) 
- Medienpicker (z.B. Bilder aus dem Medienpool auswählen / aus festgelegter Kategorie) 
- Link-Picker (z.B. Linklist). 

Die Dinger sollten möglichst unabhängig vom verwendeten Frontend-Design (Bootstrap, UiKit oder Eigenentwicklung) funktionieren. (evtl. Shadow-DOM / Web Component) 

Ich habe mir bislang immer mit Selects geholfen, was aber für die Zielgruppe der Frontenduser nicht wirklich smart ist und bei  vielen Datensätzen auch nicht komfortabel ist. 

Habt Ihr da evtl. schon einen Lösungsansatz? 

Eine Idee: 
Vielleicht wäre auch ein "leeres" Widget eine Lösung das man nach Belieben mit Daten befüllen kann also ein Placeholder der über eine API den gewünschten Picker liefert.

**Comment by dergel** [comment]
sorry, nach fast exakt 4 Jahren :) .. sehe ich nicht hier, aber ist sicher auch nicht mehr so das Thema, oder?

**Comment by skerbis** [comment]
Jupp gehörte wohl eher zu YForm
