### ISSUE TITLE
UX: Einstellungen startet auf der Dokumentation, nicht auf "Authentifizierung"

### ISSUE THREAD

**Issue by alxndr-w** [yakamara/ycom#376]

**Comment by alxndr-w** [comment]
Ich könnte mir vorstellen, dass sich das Problem umgehen ließe, indem Das Addon eine leere Einstellungsseite liefert mit dem Hinweis, Plugins zu installieren - und sich das auth-Plugin mit seiner Einstellungsseite als Subpage registriert.

**Comment by dergel** [comment]
Das werde ich ändern, sobald ich die PlugIns entfernt habe und alle als ein AddOn umbauen

https://github.com/yakamara/redaxo_ycom/issues/430

**Comment by alxndr-w** [comment]
Wenn das sowieso durch den Wegfall von Plugins sich erübrigt, mache ich hier zu.
