### ISSUE TITLE
Tabelle rex_ycom_user readonly setzen?

### ISSUE THREAD

**Issue by tbaddade** [yakamara/ycom#451]
Die YCom User Tabelle kann man via YForm für sich anpassen/modifizieren. 

Leider, aber auch ganz legitim, passt YCom nach einem Update diese Tabelle für sich ebenfalls an. Daher fände ich es gut, wenn man diese Tabelle gar nicht via YForm anpassen könnte und man Stammdaten zu einem YCom User wie Vorname / Name / Nachname etc. eher in einer separaten Tabelle speichert.

**Comment by dergel** [comment]
Das müsste zunächst in YForm ermöglicht werden und ich glaube, das ist erst mal unrealistisch, dass das passieren wird.

**Comment by tbaddade** [comment]
Dann wäre es gut die Update-Routine anzupassen.
Ich hatte nach Updates (auch mehrere hintereinander) mehrfach verschiedene Felder in der Tabelle.

**Comment by dergel** [comment]
Wäre interessant, ob es von 3.0 auf 4er-Version ist. Ansonsten wäre ein Beispiel hilfreich.
