### ISSUE TITLE
Multidomain Login

### ISSUE THREAD

**Issue by georgkaser** [yakamara/ycom#456]
Hi, ich hab den Fall dass ich für eine Multidomain Website ein Login machen muss.
Ich hab 5 Domains, alle in einer REDAXO Installation mit yrewrite:

- domain1.de
- domain2.de
- domain3.de
- domain4.de
- domain5.de

Im Header ist immer ein Login Button. Dafür hab ich eine weitere Domain in yrewrite angelegt: 
- login.domain1.de

Wenn ich mich jetzt da einlogge, bin ich ja verständlicherweise nur unter dieser Domain eingeloggt. Jetzt hab ich aber gelesen, dass das mit Multidomain auch möglich ist - nämlich hier: 

https://friendsofredaxo.github.io/tricks/addons/ycom/keep_logged_in_accross_subdomain_change

Klappt aber bei mir nicht - ist das nicht mehr aktuell?

**Comment by alxndr-w** [comment]
Gibt's hieran noch Interesse?

**Comment by georgkaser** [comment]
Nein, im Moment nicht. Ich habs gelöst - aber ideal ist das alles nicht. Ich werde zukünftig eher vermeiden mehrere Domains in einer REDAXO Installation (also unterschiedliche Webseiten mit dem selben Layout), weil es nicht nur hier Probleme macht. Auch anderweitig ist das eher nicht optimal sobald es etwas komplexer wird. Aber Danke.

**Comment by alxndr-w** [comment]
In der Anleitung bei den Tricks ist alles dieselbe Domain (nur unterschiedliche Subdomains), daher hat das bei dir vermutlich nicht funktioniert.

**Comment by dergel** [comment]
Im Prinzip müsste man ein SSO in der eigenen Webseite integrieren. Das ist eher aufwändig. Ich versuche das mit den verschiedenen Domains auch zu vermeiden, mache dann Subdomains, oder eine Hauptdomain, die für den Loginbereich zuständig ist.
