### ISSUE TITLE
BUG: isInGroup() liefert immer false zurück

### ISSUE THREAD

**Issue by iceman-fx** [yakamara/ycom#464]
In der v4.2 wurde die in_array-Prüfung auf strict gesetzt, was nun dazu führt, dass der übergebene INT-Wert nicht mehr mit dem STRING-Wert aus dem explode()-Array übereinstimmt.

- explode() liefert STRING-Werte im Array zurück
- int $group_id passt dazu nicht mehr

**Comment by eaCe** [comment]
Ist gefixt, kann geschlossen werden: https://github.com/yakamara/redaxo_ycom/pull/460

**Comment by paddle07** [comment]
Im aktuellen Release (4.2.0) liefert isInGroup() immer noch false ... (STRICT mit int und string ...). Was wurde gefixt?

**Comment by eaCe** [comment]
@paddle07 im Release ist der Code auch nicht drin, gerne mal mit der Github Version testen

**Comment by paddle07** [comment]
@eaCe ja, die Änderung in Github gerade gesehen. Danke.
