### ISSUE TITLE
Dokumentation Passwort-Zurücksetzen-Fromular: captcha wurde aus YForm entfernt

### ISSUE THREAD

**Issue by akuehnis** [yakamara/ycom#470]
In der Dokumentation von YCom 4.2 steht noch: 
```
captcha|Bitte geben Sie den entsprechenden Sicherheitscode ein. Sollten Sie den Code nicht lesen können klicken Sie bitte auf die Grafik, um einen neuen Code zu generieren.|Sie haben den Sicherheitscode falsch eingegeben.
```

captcha gibt es aber anscheinend in YForm nicht mehr, es funktioniert nicht.

**Comment by eaCe** [comment]
Yup, Captcha wurde in YForm 4 entfernt: https://github.com/yakamara/yform/blob/master/CHANGELOG.md#deprecated--entfernt
Gerne einen PR erstellen.

**Comment by alxndr-w** [comment]
PR welcome

**Comment by dergel** [comment]
ist korrigiert
