### ISSUE TITLE
returnTo funktioniert nicht, wenn keine article_id_logout gesetzt ist

### ISSUE THREAD

**Issue by goldfoot** [yakamara/ycom#488]
Wenn ich es richtig verstehe, soll in [`rex_ycom_auth\cleanReferer()`](https://github.com/yakamara/ycom/blob/03c893a645ff8bc1509010e1ee2a65e236e3646f/plugins/auth/lib/ycom_auth.php#L563)  in [Zeile 589](https://github.com/yakamara/ycom/blob/03c893a645ff8bc1509010e1ee2a65e236e3646f/plugins/auth/lib/ycom_auth.php#L589) geprüft werden, ob die Referrer-URL direkt wieder auf den Logout führt. Um ein direktes Ein- und Ausloggen zu verhindert, wird in diesem Fall die `$returnUrl` und damit der `returnTo`-Parameter entfernt.

Dies führt dazu, dass `returnTo` nicht mehr funktioniert, wenn in den Einstellungen kein `article_id_logout` gesetzt ist. Dies kann jedoch der Fall sein, falls kein Logout gewünscht ist.

Ich schlage daher vor, dass zusätzlich geprüft wird, ob `article_id_logout` überhaupt gesetzt wurde:
[ycom_auth.php](https://github.com/yakamara/ycom/blob/master/plugins/auth/lib/ycom_auth.php):

```diff
*** 585,593 ****
          if (isset($url['query']) && '' != $url['query']) {
              $returnUrl .= '?' . $url['query'];
          }

!         $referer_to_logout = strpos($returnUrl, rex_getUrl(rex_config::get('ycom/auth', 'article_id_logout', '')));
          if (false === $referer_to_logout) {
          } else {
              $returnUrl = '';
          }
--- 585,599 ----
          if (isset($url['query']) && '' != $url['query']) {
              $returnUrl .= '?' . $url['query'];
          }

!         $article_id_logout = rex_config::get('ycom/auth', 'article_id_logout', '');
!         if ($article_id_logout > 0) {
!             $referer_to_logout = strpos($returnUrl, rex_getUrl(rex_config::get('ycom/auth', 'article_id_logout', '')));
!         } else {
!             $referer_to_logout = false;
!         }
!
          if (false === $referer_to_logout) {
          } else {
              $returnUrl = '';
          }
```

**Comment by dergel** [comment]
Vielen Dank. Ja, stimmt. Habe deine Änderungen übernommen. https://github.com/yakamara/ycom/commit/0bf7427918182c5c05021d5ff5fed85e8f834f86
